version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: survey_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=survey_system
    networks:
      - survey_network

  backend:
    build: .
    container_name: survey_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/survey_system
      - PORT=5000
    networks:
      - survey_network

  frontend:
    image: node:alpine
    container_name: survey_frontend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - backend
    networks:
      - survey_network

volumes:
  mongodb_data:

networks:
  survey_network:
    driver: bridge
